name: image
on:
  push:
    tags: ['*-fv*']          # e.g. 1.37.3-fv1
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - run: sudo apt-get install -y -qq libcairo2
      - run: pip install cairosvg
      - run: IMAGE_TAG="${GITHUB_REF_NAME}" bash scripts/build-web-vault.sh
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          file: docker/Dockerfile.debian
          push: true
          tags: |
            ghcr.io/euayyelo-tech/fastvault-server:${{ github.ref_name }}
            ghcr.io/euayyelo-tech/fastvault-server:latest
